server:
  port: 8080

spring:
  # 当前应用的名称（如果不配置默认为当前的项目名）
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    password :
    #操作的是0号数据库
    database: 0
    jedis:
      #Redis连接池配置
      pool:
        #最大连接数
        max-active: 8
        #连接池最大阻塞等待时间
        max-wait: 1ms
        #连接池中的最大空闲连接
        max-idle: 4
        #连接池中的最小空闲连接
        min-idle: 0
  cache:
    redis:
      # 设置缓存有效期 - 30 min
      time-to-live: 1800000

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 配置 MP 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置MyBatis-Plus的主键策略 - 基于雪花算法
      id-type: ASSIGN_ID

# 自定义配置
reggie:
  file:
    # windows
    path: D:\img\


